version: '3.2'

# Use the default driver (here bridge)
networks:
  beacon-priv:
  idp-priv:
  pub:

services:

  db:
    environment:
      - PGDATA=/beacon-db
      - POSTGRES_USER=beacon
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=beacon
    hostname: beacon-db
    container_name: beacon-db
    image: postgres:12-alpine
    volumes:
      - ./db/schema.sql.gz:/docker-entrypoint-initdb.d/1.sql.gz
      - ./db/data.sql.gz:/docker-entrypoint-initdb.d/2.sql.gz
    networks:
      - beacon-priv
    ports:
      - "5055:5432"


  beacon:
    build: ..
    image: egarchive/beacon:2.0
    hostname: beacon
    container_name: beacon
    volumes:
      - ../beacon:/beacon/beacon  # inject the code, so we see the modifications "live"
      - ../ui/static:/beacon/ui/static
      - ../ui/templates:/beacon/ui/templates
      - ./conf.py:/beacon/beacon/conf.py
      - ./logger.yml:/beacon/beacon/logger.yml
    ports:
      - "5050:5050"
    networks:
      - beacon-priv
      - pub
    entrypoint: ['/bin/sleep','100000000']
    # working_dir: '/beacon'
    # entrypoint: ['python','-m','beacon']

  ###########################################
  # Dummy Permissions server
  ###########################################
  permissions:
    image: egarchive/beacon:2.0
    hostname: beacon-permissions
    container_name: beacon-permissions
    volumes:
      - ./permissions.py:/beacon/permissions.py  # inject the code, so we see the modifications "live"
      - ./logger.yml:/beacon/logger.yml
    ports:
      - "5051:5051"
    networks:
      - beacon-priv
      - pub
    #entrypoint: ['/bin/sleep','100000000']
    working_dir: '/beacon'
    entrypoint: ['python','permissions.py']
    
  ###########################################
  # Local Identity Provider
  ###########################################
  # Keycloak is so slow to boot that the DB goes faster
  # and we don't need a delay in-between. We can rely on the depends_on only.
  idp:
    image: jboss/keycloak
    hostname: idp
    container_name: idp
    environment:
      # - KEYCLOAK_FRONTEND_URL=http://idp:8080/auth
      # - KEYCLOAK_LOGLEVEL=DEBUG
      # - ROOT_LOGLEVEL=DEBUG
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=secret
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_VENDOR=postgres
      - DB_ADDR=idp-db
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      #- DB_SCHEMA=public
      - KEYCLOAK_IMPORT=/tmp/beacon-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled
    volumes:
      - ./beacon-realm.json:/tmp/beacon-realm.json
    ports:
      - "8080:8080"
    networks:
      - pub
      - idp-priv
    depends_on:
      - idp-db

  idp-db:
    image: postgres
    hostname: idp-db
    container_name: idp-db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    networks:
      - idp-priv

